/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProbisRouteImport } from './routes/dashboard/probis'
import { Route as DashboardPlanningRouteImport } from './routes/dashboard/planning'
import { Route as DashboardOpdRouteImport } from './routes/dashboard/opd'
import { Route as DashboardLayananRouteImport } from './routes/dashboard/layanan'
import { Route as DashboardKeamananRouteImport } from './routes/dashboard/keamanan'
import { Route as DashboardInfrastrukturRouteImport } from './routes/dashboard/infrastruktur'
import { Route as DashboardDataRouteImport } from './routes/dashboard/data'
import { Route as DashboardAplikasiRouteImport } from './routes/dashboard/aplikasi'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProbisRoute = DashboardProbisRouteImport.update({
  id: '/probis',
  path: '/probis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanningRoute = DashboardPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpdRoute = DashboardOpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLayananRoute = DashboardLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeamananRoute = DashboardKeamananRouteImport.update({
  id: '/keamanan',
  path: '/keamanan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfrastrukturRoute = DashboardInfrastrukturRouteImport.update({
  id: '/infrastruktur',
  path: '/infrastruktur',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDataRoute = DashboardDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAplikasiRoute = DashboardAplikasiRouteImport.update({
  id: '/aplikasi',
  path: '/aplikasi',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/aplikasi': typeof DashboardAplikasiRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/infrastruktur': typeof DashboardInfrastrukturRoute
  '/dashboard/keamanan': typeof DashboardKeamananRoute
  '/dashboard/layanan': typeof DashboardLayananRoute
  '/dashboard/opd': typeof DashboardOpdRoute
  '/dashboard/planning': typeof DashboardPlanningRoute
  '/dashboard/probis': typeof DashboardProbisRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/aplikasi': typeof DashboardAplikasiRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/infrastruktur': typeof DashboardInfrastrukturRoute
  '/dashboard/keamanan': typeof DashboardKeamananRoute
  '/dashboard/layanan': typeof DashboardLayananRoute
  '/dashboard/opd': typeof DashboardOpdRoute
  '/dashboard/planning': typeof DashboardPlanningRoute
  '/dashboard/probis': typeof DashboardProbisRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/aplikasi': typeof DashboardAplikasiRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/infrastruktur': typeof DashboardInfrastrukturRoute
  '/dashboard/keamanan': typeof DashboardKeamananRoute
  '/dashboard/layanan': typeof DashboardLayananRoute
  '/dashboard/opd': typeof DashboardOpdRoute
  '/dashboard/planning': typeof DashboardPlanningRoute
  '/dashboard/probis': typeof DashboardProbisRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/aplikasi'
    | '/dashboard/data'
    | '/dashboard/infrastruktur'
    | '/dashboard/keamanan'
    | '/dashboard/layanan'
    | '/dashboard/opd'
    | '/dashboard/planning'
    | '/dashboard/probis'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/aplikasi'
    | '/dashboard/data'
    | '/dashboard/infrastruktur'
    | '/dashboard/keamanan'
    | '/dashboard/layanan'
    | '/dashboard/opd'
    | '/dashboard/planning'
    | '/dashboard/probis'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/aplikasi'
    | '/dashboard/data'
    | '/dashboard/infrastruktur'
    | '/dashboard/keamanan'
    | '/dashboard/layanan'
    | '/dashboard/opd'
    | '/dashboard/planning'
    | '/dashboard/probis'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/probis': {
      id: '/dashboard/probis'
      path: '/probis'
      fullPath: '/dashboard/probis'
      preLoaderRoute: typeof DashboardProbisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/planning': {
      id: '/dashboard/planning'
      path: '/planning'
      fullPath: '/dashboard/planning'
      preLoaderRoute: typeof DashboardPlanningRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/opd': {
      id: '/dashboard/opd'
      path: '/opd'
      fullPath: '/dashboard/opd'
      preLoaderRoute: typeof DashboardOpdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/layanan': {
      id: '/dashboard/layanan'
      path: '/layanan'
      fullPath: '/dashboard/layanan'
      preLoaderRoute: typeof DashboardLayananRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keamanan': {
      id: '/dashboard/keamanan'
      path: '/keamanan'
      fullPath: '/dashboard/keamanan'
      preLoaderRoute: typeof DashboardKeamananRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/infrastruktur': {
      id: '/dashboard/infrastruktur'
      path: '/infrastruktur'
      fullPath: '/dashboard/infrastruktur'
      preLoaderRoute: typeof DashboardInfrastrukturRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data': {
      id: '/dashboard/data'
      path: '/data'
      fullPath: '/dashboard/data'
      preLoaderRoute: typeof DashboardDataRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/aplikasi': {
      id: '/dashboard/aplikasi'
      path: '/aplikasi'
      fullPath: '/dashboard/aplikasi'
      preLoaderRoute: typeof DashboardAplikasiRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAplikasiRoute: typeof DashboardAplikasiRoute
  DashboardDataRoute: typeof DashboardDataRoute
  DashboardInfrastrukturRoute: typeof DashboardInfrastrukturRoute
  DashboardKeamananRoute: typeof DashboardKeamananRoute
  DashboardLayananRoute: typeof DashboardLayananRoute
  DashboardOpdRoute: typeof DashboardOpdRoute
  DashboardPlanningRoute: typeof DashboardPlanningRoute
  DashboardProbisRoute: typeof DashboardProbisRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAplikasiRoute: DashboardAplikasiRoute,
  DashboardDataRoute: DashboardDataRoute,
  DashboardInfrastrukturRoute: DashboardInfrastrukturRoute,
  DashboardKeamananRoute: DashboardKeamananRoute,
  DashboardLayananRoute: DashboardLayananRoute,
  DashboardOpdRoute: DashboardOpdRoute,
  DashboardPlanningRoute: DashboardPlanningRoute,
  DashboardProbisRoute: DashboardProbisRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
